---
title: "R Basics"
author: "Liang Bo Wang"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: false
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


# Basic Algebra

## Mathematical operations are vectorized

By default, opreations are element-wise and will be **broadcasted** to each pair of inputs.

```{r}
1:5 + 6:10
c(9, 5, 2, 7) * c(5, 5, 6, 6)
689 > 609
1:3 == 3:1
```

## Numerical comparison
Don't use `==` or `!=` to compare numbers, which easily gives round-off errors. Float numbers (e.g. 1.414 and 55.66) have precision limit 

```{r}
sqrt(1:5) ^ 2 == 1:5
all.equal(sqrt(1:5) ^ 2, 1:5)
all.equal(sqrt(2) ^ 2, 3)
isTRUE(all.equal(sqrt(2) ^ 2, 3))
```

## Vectors and Variables

```{r}
x <- 1:5
y <- c(-1, 1, 2, 3:4)
x - y
all(x^2 >= 1)
any(y < 0)
(y > 0) & (y ^ 2 < 3)
```


## Strings and Factors

```{r}
c("Bioinfo", "and", "Biostat", "Core", "Lab")
(gender <- factor(
    c("male", "female", "male", "female", "female")
))
levels(gender)
as.integer(gender)  # convert factor into integers
```



